# Generated by Django 2.0 on 2019-09-16 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190908_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='teacher/%Y/%m', verbose_name='头像'),
            preserve_default=False,
        ),
    ]
