# Generated by Django 2.0 on 2019-10-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.IntegerField(default=0, verbose_name='课程类别'),
        ),
    ]
