# Generated by Django 2.0 on 2019-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='课程标记'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.IntegerField(default='后端开发', verbose_name='课程类别'),
        ),
    ]
