# Generated by Django 2.0 on 2019-10-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191013_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tag',
            new_name='tags',
        ),
    ]
